version: '3.8'

services:
  # Streamlit Application (Development)
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8504"  # Map local 8501 to container 8504
    environment:
      - PORT=8504
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FASTAPI_URL=http://fastapi:8000
    env_file:
      - .env.local
    volumes:
      # Mount source code for live development
      - ./stravatalk:/app/stravatalk
      - ./streamlit_login_app.py:/app/streamlit_login_app.py
      - ./templates:/app/templates
    restart: unless-stopped
    depends_on:
      - fastapi
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8504/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # FastAPI Services (Development)
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - STRAVA_WEBHOOK_VERIFY_TOKEN=${STRAVA_WEBHOOK_VERIFY_TOKEN}
      - OAUTH_REDIRECT_URI=${OAUTH_REDIRECT_URI}
      - WEBHOOK_CALLBACK_URL=${WEBHOOK_CALLBACK_URL}
      - FASTAPI_URL=http://localhost:8000
      - STREAMLIT_URL=http://localhost:8501
      - JWT_SECRET=${JWT_SECRET}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - FROM_EMAIL=${FROM_EMAIL}
    env_file:
      - .env.local
    volumes:
      # Mount source code for live development
      - ./stravatalk:/app/stravatalk
      - ./templates:/app/templates
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: stravatalk-dev-network